name: Docs Generation & Deployment
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy-docs:
    name: Build & deploy docs
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: 0

      - name: Install/Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@v1.1.2
        with:
          packages: doxygen sphinx-doc
          version: 1.0

      - name: Install dependencies
        run: |
          pip3 install sphinx-rtd-theme breathe sphinx-sitemap m2r2
          pip3 uninstall mistune -y
          pip3 install mistune==0.8.4

      - name: Generate docs
        run: |
          cd docs
          make html
          cd _build/html
          touch .nojekyll

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/_build/html
